#include "console.h"

void print_turrnut_logo() {
    char block[2] = { 219, '\0' };
    set_color(BLACK_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(YELLOW_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(RED_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(YELLOW_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(YELLOW_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(RED_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(YELLOW_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(YELLOW_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(RED_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(RED_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(RED_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(RED_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(RED_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(LIGHT_GREEN_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();

    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(WHITE_COLOR, BLACK_COLOR);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    print(block);
    set_color(BLACK_COLOR, BLACK_COLOR);
    newline();
}